/** Indicativos E.164 para o seletor de telefone dos formulários do site. */

export interface DialCountry {
  iso: string;
  dial: string;
  pt: string;
  en: string;
}

/** Comuns primeiro, pela ordem pedida. */
export const COMMON_ISO = [
  'PT',
  'ES',
  'FR',
  'GB',
  'BR',
  'DE',
  'IT',
  'US',
  'AO',
  'CH',
  'BE',
  'NL',
  'IE',
  'MZ',
  'CV',
] as const;

type DialRow = [iso: string, dial: string, pt: string, en: string];

const ROWS: DialRow[] = [
  ['AF', '93', 'Afeganistão', 'Afghanistan'],
  ['AL', '355', 'Albânia', 'Albania'],
  ['DZ', '213', 'Argélia', 'Algeria'],
  ['AD', '376', 'Andorra', 'Andorra'],
  ['AO', '244', 'Angola', 'Angola'],
  ['AG', '1268', 'Antígua e Barbuda', 'Antigua and Barbuda'],
  ['AR', '54', 'Argentina', 'Argentina'],
  ['AM', '374', 'Arménia', 'Armenia'],
  ['AU', '61', 'Austrália', 'Australia'],
  ['AT', '43', 'Áustria', 'Austria'],
  ['AZ', '994', 'Azerbaijão', 'Azerbaijan'],
  ['BS', '1242', 'Baamas', 'Bahamas'],
  ['BH', '973', 'Barém', 'Bahrain'],
  ['BD', '880', 'Bangladeche', 'Bangladesh'],
  ['BB', '1246', 'Barbados', 'Barbados'],
  ['BY', '375', 'Bielorrússia', 'Belarus'],
  ['BE', '32', 'Bélgica', 'Belgium'],
  ['BZ', '501', 'Belize', 'Belize'],
  ['BJ', '229', 'Benim', 'Benin'],
  ['BT', '975', 'Butão', 'Bhutan'],
  ['BO', '591', 'Bolívia', 'Bolivia'],
  ['BA', '387', 'Bósnia e Herzegovina', 'Bosnia and Herzegovina'],
  ['BW', '267', 'Botsuana', 'Botswana'],
  ['BR', '55', 'Brasil', 'Brazil'],
  ['BN', '673', 'Brunei', 'Brunei'],
  ['BG', '359', 'Bulgária', 'Bulgaria'],
  ['BF', '226', 'Burquina Faso', 'Burkina Faso'],
  ['BI', '257', 'Burundi', 'Burundi'],
  ['KH', '855', 'Camboja', 'Cambodia'],
  ['CM', '237', 'Camarões', 'Cameroon'],
  ['CA', '1', 'Canadá', 'Canada'],
  ['CV', '238', 'Cabo Verde', 'Cape Verde'],
  ['CF', '236', 'República Centro-Africana', 'Central African Republic'],
  ['TD', '235', 'Chade', 'Chad'],
  ['CL', '56', 'Chile', 'Chile'],
  ['CN', '86', 'China', 'China'],
  ['CO', '57', 'Colômbia', 'Colombia'],
  ['KM', '269', 'Comores', 'Comoros'],
  ['CG', '242', 'Congo', 'Congo'],
  ['CD', '243', 'RD Congo', 'DR Congo'],
  ['CR', '506', 'Costa Rica', 'Costa Rica'],
  ['CI', '225', 'Costa do Marfim', "Côte d'Ivoire"],
  ['HR', '385', 'Croácia', 'Croatia'],
  ['CU', '53', 'Cuba', 'Cuba'],
  ['CY', '357', 'Chipre', 'Cyprus'],
  ['CZ', '420', 'Chéquia', 'Czechia'],
  ['DK', '45', 'Dinamarca', 'Denmark'],
  ['DJ', '253', 'Jibuti', 'Djibouti'],
  ['DM', '1767', 'Domínica', 'Dominica'],
  ['DO', '1809', 'República Dominicana', 'Dominican Republic'],
  ['EC', '593', 'Equador', 'Ecuador'],
  ['EG', '20', 'Egito', 'Egypt'],
  ['SV', '503', 'El Salvador', 'El Salvador'],
  ['GQ', '240', 'Guiné Equatorial', 'Equatorial Guinea'],
  ['ER', '291', 'Eritreia', 'Eritrea'],
  ['EE', '372', 'Estónia', 'Estonia'],
  ['SZ', '268', 'Essuatíni', 'Eswatini'],
  ['ET', '251', 'Etiópia', 'Ethiopia'],
  ['FJ', '679', 'Fiji', 'Fiji'],
  ['FI', '358', 'Finlândia', 'Finland'],
  ['FR', '33', 'França', 'France'],
  ['GA', '241', 'Gabão', 'Gabon'],
  ['GM', '220', 'Gâmbia', 'Gambia'],
  ['GE', '995', 'Geórgia', 'Georgia'],
  ['DE', '49', 'Alemanha', 'Germany'],
  ['GH', '233', 'Gana', 'Ghana'],
  ['GR', '30', 'Grécia', 'Greece'],
  ['GD', '1473', 'Granada', 'Grenada'],
  ['GT', '502', 'Guatemala', 'Guatemala'],
  ['GN', '224', 'Guiné', 'Guinea'],
  ['GW', '245', 'Guiné-Bissau', 'Guinea-Bissau'],
  ['GY', '592', 'Guiana', 'Guyana'],
  ['HT', '509', 'Haiti', 'Haiti'],
  ['HN', '504', 'Honduras', 'Honduras'],
  ['HK', '852', 'Hong Kong', 'Hong Kong'],
  ['HU', '36', 'Hungria', 'Hungary'],
  ['IS', '354', 'Islândia', 'Iceland'],
  ['IN', '91', 'Índia', 'India'],
  ['ID', '62', 'Indonésia', 'Indonesia'],
  ['IR', '98', 'Irão', 'Iran'],
  ['IQ', '964', 'Iraque', 'Iraq'],
  ['IE', '353', 'Irlanda', 'Ireland'],
  ['IL', '972', 'Israel', 'Israel'],
  ['IT', '39', 'Itália', 'Italy'],
  ['JM', '1876', 'Jamaica', 'Jamaica'],
  ['JP', '81', 'Japão', 'Japan'],
  ['JO', '962', 'Jordânia', 'Jordan'],
  ['KZ', '7', 'Cazaquistão', 'Kazakhstan'],
  ['KE', '254', 'Quénia', 'Kenya'],
  ['KI', '686', 'Quiribáti', 'Kiribati'],
  ['KW', '965', 'Koweit', 'Kuwait'],
  ['KG', '996', 'Quirguistão', 'Kyrgyzstan'],
  ['LA', '856', 'Laos', 'Laos'],
  ['LV', '371', 'Letónia', 'Latvia'],
  ['LB', '961', 'Líbano', 'Lebanon'],
  ['LS', '266', 'Lesoto', 'Lesotho'],
  ['LR', '231', 'Libéria', 'Liberia'],
  ['LY', '218', 'Líbia', 'Libya'],
  ['LI', '423', 'Listenstaine', 'Liechtenstein'],
  ['LT', '370', 'Lituânia', 'Lithuania'],
  ['LU', '352', 'Luxemburgo', 'Luxembourg'],
  ['MO', '853', 'Macau', 'Macau'],
  ['MG', '261', 'Madagáscar', 'Madagascar'],
  ['MW', '265', 'Maláui', 'Malawi'],
  ['MY', '60', 'Malásia', 'Malaysia'],
  ['MV', '960', 'Maldivas', 'Maldives'],
  ['ML', '223', 'Mali', 'Mali'],
  ['MT', '356', 'Malta', 'Malta'],
  ['MH', '692', 'Ilhas Marshall', 'Marshall Islands'],
  ['MR', '222', 'Mauritânia', 'Mauritania'],
  ['MU', '230', 'Maurícia', 'Mauritius'],
  ['MX', '52', 'México', 'Mexico'],
  ['FM', '691', 'Micronésia', 'Micronesia'],
  ['MD', '373', 'Moldávia', 'Moldova'],
  ['MC', '377', 'Mónaco', 'Monaco'],
  ['MN', '976', 'Mongólia', 'Mongolia'],
  ['ME', '382', 'Montenegro', 'Montenegro'],
  ['MA', '212', 'Marrocos', 'Morocco'],
  ['MZ', '258', 'Moçambique', 'Mozambique'],
  ['MM', '95', 'Mianmar', 'Myanmar'],
  ['NA', '264', 'Namíbia', 'Namibia'],
  ['NR', '674', 'Nauru', 'Nauru'],
  ['NP', '977', 'Nepal', 'Nepal'],
  ['NL', '31', 'Países Baixos', 'Netherlands'],
  ['NZ', '64', 'Nova Zelândia', 'New Zealand'],
  ['NI', '505', 'Nicarágua', 'Nicaragua'],
  ['NE', '227', 'Níger', 'Niger'],
  ['NG', '234', 'Nigéria', 'Nigeria'],
  ['KP', '850', 'Coreia do Norte', 'North Korea'],
  ['MK', '389', 'Macedónia do Norte', 'North Macedonia'],
  ['NO', '47', 'Noruega', 'Norway'],
  ['OM', '968', 'Omã', 'Oman'],
  ['PK', '92', 'Paquistão', 'Pakistan'],
  ['PW', '680', 'Palau', 'Palau'],
  ['PS', '970', 'Palestina', 'Palestine'],
  ['PA', '507', 'Panamá', 'Panama'],
  ['PG', '675', 'Papua-Nova Guiné', 'Papua New Guinea'],
  ['PY', '595', 'Paraguai', 'Paraguay'],
  ['PE', '51', 'Peru', 'Peru'],
  ['PH', '63', 'Filipinas', 'Philippines'],
  ['PL', '48', 'Polónia', 'Poland'],
  ['PT', '351', 'Portugal', 'Portugal'],
  ['QA', '974', 'Catar', 'Qatar'],
  ['RO', '40', 'Roménia', 'Romania'],
  ['RU', '7', 'Rússia', 'Russia'],
  ['RW', '250', 'Ruanda', 'Rwanda'],
  ['KN', '1869', 'São Cristóvão e Neves', 'Saint Kitts and Nevis'],
  ['LC', '1758', 'Santa Lúcia', 'Saint Lucia'],
  ['VC', '1784', 'São Vicente e Granadinas', 'Saint Vincent and the Grenadines'],
  ['WS', '685', 'Samoa', 'Samoa'],
  ['SM', '378', 'São Marinho', 'San Marino'],
  ['ST', '239', 'São Tomé e Príncipe', 'Sao Tome and Principe'],
  ['SA', '966', 'Arábia Saudita', 'Saudi Arabia'],
  ['SN', '221', 'Senegal', 'Senegal'],
  ['RS', '381', 'Sérvia', 'Serbia'],
  ['SC', '248', 'Seicheles', 'Seychelles'],
  ['SL', '232', 'Serra Leoa', 'Sierra Leone'],
  ['SG', '65', 'Singapura', 'Singapore'],
  ['SK', '421', 'Eslováquia', 'Slovakia'],
  ['SI', '386', 'Eslovénia', 'Slovenia'],
  ['SB', '677', 'Ilhas Salomão', 'Solomon Islands'],
  ['SO', '252', 'Somália', 'Somalia'],
  ['ZA', '27', 'África do Sul', 'South Africa'],
  ['KR', '82', 'Coreia do Sul', 'South Korea'],
  ['SS', '211', 'Sudão do Sul', 'South Sudan'],
  ['ES', '34', 'Espanha', 'Spain'],
  ['LK', '94', 'Sri Lanca', 'Sri Lanka'],
  ['SD', '249', 'Sudão', 'Sudan'],
  ['SR', '597', 'Suriname', 'Suriname'],
  ['SE', '46', 'Suécia', 'Sweden'],
  ['CH', '41', 'Suíça', 'Switzerland'],
  ['SY', '963', 'Síria', 'Syria'],
  ['TW', '886', 'Taiwan', 'Taiwan'],
  ['TJ', '992', 'Tajiquistão', 'Tajikistan'],
  ['TZ', '255', 'Tanzânia', 'Tanzania'],
  ['TH', '66', 'Tailândia', 'Thailand'],
  ['TL', '670', 'Timor-Leste', 'Timor-Leste'],
  ['TG', '228', 'Togo', 'Togo'],
  ['TO', '676', 'Tonga', 'Tonga'],
  ['TT', '1868', 'Trindade e Tobago', 'Trinidad and Tobago'],
  ['TN', '216', 'Tunísia', 'Tunisia'],
  ['TR', '90', 'Turquia', 'Turkey'],
  ['TM', '993', 'Turquemenistão', 'Turkmenistan'],
  ['TV', '688', 'Tuvalu', 'Tuvalu'],
  ['UG', '256', 'Uganda', 'Uganda'],
  ['UA', '380', 'Ucrânia', 'Ukraine'],
  ['AE', '971', 'Emirados Árabes Unidos', 'United Arab Emirates'],
  ['GB', '44', 'Reino Unido', 'United Kingdom'],
  ['US', '1', 'Estados Unidos', 'United States'],
  ['UY', '598', 'Uruguai', 'Uruguay'],
  ['UZ', '998', 'Uzbequistão', 'Uzbekistan'],
  ['VU', '678', 'Vanuatu', 'Vanuatu'],
  ['VA', '379', 'Vaticano', 'Vatican City'],
  ['VE', '58', 'Venezuela', 'Venezuela'],
  ['VN', '84', 'Vietname', 'Vietnam'],
  ['YE', '967', 'Iémen', 'Yemen'],
  ['ZM', '260', 'Zâmbia', 'Zambia'],
  ['ZW', '263', 'Zimbábue', 'Zimbabwe'],
];

export const COUNTRIES: DialCountry[] = ROWS.map(([iso, dial, pt, en]) => ({
  iso,
  dial: `+${dial}`,
  pt,
  en,
}));

const BY_ISO = new Map(COUNTRIES.map((c) => [c.iso, c]));

export function countryByIso(iso: string): DialCountry | undefined {
  return BY_ISO.get(iso.toUpperCase());
}

export function commonCountries(): DialCountry[] {
  return COMMON_ISO.map((iso) => BY_ISO.get(iso)).filter((c): c is DialCountry => !!c);
}

export function restCountries(): DialCountry[] {
  const common = new Set<string>(COMMON_ISO);
  return COUNTRIES.filter((c) => !common.has(c.iso));
}
